### ISSUE TITLE
Segmentation fault in ecma_arraybuffer_new_object

### ISSUE THREAD

**Issue by renatahodovan** [jerryscript-project/jerryscript#1616]
###### Jerry version:

```
Checked revision: 62a581f
Build: debug.linux
```
###### OS:

```
Ubuntu 16.04.2 LTS
```
###### Test case:

```javascript
var a = new ArrayBuffer (0xfffffffe)
```

###### Build command:
```
tools/build.py --clean --debug --profile=es2015-subset --compile-flag=-m32 --system-allocator=on --jerry-libc=off
```
###### Backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x080d6c8a in __memset_sse2_rep ()
(gdb) bt
#0  0x080d6c8a in __memset_sse2_rep ()
#1  0x08076159 in ecma_arraybuffer_new_object (length=4294967294) at jerryscript/jerry-core/ecma/operations/ecma-arraybuffer-object.c:99
#2  0x080760d4 in ecma_op_create_arraybuffer_object (arguments_list_p=0xffffc064, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-arraybuffer-object.c:71
#3  0x08059d51 in ecma_builtin_arraybuffer_dispatch_construct (arguments_list_p=0xffffc064, arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-arraybuffer.c:94
#4  0x0809aea4 in ecma_builtin_dispatch_construct (obj_p=0x837e7b8, arguments_list_p=0xffffc064, arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.inc.h:312
#5  0x0807c943 in ecma_op_function_construct (func_obj_p=0x837e7b8, arguments_list_p=0xffffc064, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:712
#6  0x08062909 in opfunc_construct.lto_priv.245 (frame_ctx_p=0xffffc084) at jerryscript/jerry-core/vm/vm.c:443
#7  0x0805ae1d in vm_execute (frame_ctx_p=0xffffc084, arg_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:2656
#8  0x0805af9c in vm_run (bytecode_header_p=0x837e8d0, this_binding_value=137881147, lex_env_p=0x837e6e8, is_eval_code=false, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:2730
#9  0x0806246b in vm_run_global (bytecode_p=0x837e8d0) at jerryscript/jerry-core/vm/vm.c:211
#10 0x080b2263 in jerry_run (func_val=137881499) at jerryscript/jerry-core/jerry.c:385
#11 0x080b1beb in main (argc=3, argv=0xffffc4d4) at jerryscript/jerry-main/main-unix.c:726
```

<sup>Found by  [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

**Comment by jiangzidong** [comment]
I will check it
