### ISSUE TITLE
Segmentation fault in ecma_op_object_get_own_property

### ISSUE THREAD

**Issue by renatahodovan** [jerryscript-project/jerryscript#1622]
###### Jerry version:

```
Checked revision: 3de72af
Build: debug.linux
```
###### OS:

```
Ubuntu 16.04.2 LTS
```
###### Test case:

```javascript
for (var a in new Int8Array(123));
```

###### Build command:

```
./tools/build.py --clean --debug --compile-flag=-m32 --system-allocator=on --jerry-libc=off --profile=es2015-subset
```

###### Backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x080809ac in ecma_op_object_get_own_property (object_p=0x837e970, property_name_p=0x83804a8, property_ref_p=0x0, options=0)
    at jerryscript/jerry-core/ecma/operations/ecma-objects.c:156
156             property_ref_p->virtual_value = value;
bt
#0  0x080809ac in ecma_op_object_get_own_property (object_p=0x837e998, property_name_p=0x83804c0, property_ref_p=0x0, options=0) at jerryscript/jerry-core/ecma/operations/ecma-objects.c:156
#1  0x08080c95 in ecma_op_object_get_property (object_p=0x837e998, property_name_p=0x83804c0, property_ref_p=0x0, options=0) at jerryscript/jerry-core/ecma/operations/ecma-objects.c:305
#2  0x08079518 in ecma_op_object_has_property (object_p=0x837e998, property_name_p=0x83804c0) at jerryscript/jerry-core/ecma/operations/ecma-objects.c:355
#3  0x0805f525 in vm_loop.lto_priv.246 (frame_ctx_p=0xffffc084) at jerryscript/jerry-core/vm/vm.c:2172
#4  0x0805adf2 in vm_execute (frame_ctx_p=0xffffc084, arg_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:2642
#5  0x0805afd4 in vm_run (bytecode_header_p=0x837e8a8, this_binding_value=137881147, lex_env_p=0x837e6e8, is_eval_code=false, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:2730
#6  0x080624a3 in vm_run_global (bytecode_p=0x837e8a8) at jerryscript/jerry-core/vm/vm.c:211
#7  0x080b23c8 in jerry_run (func_val=137881499) at jerryscript/jerry-core/jerry.c:385
#8  0x080b1d50 in main (argc=3, argv=0xffffc4d4) at jerryscript/jerry-main/main-unix.c:726
```

<sup>Found by  [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

**Comment by jiangzidong** [comment]
I will check it
