### ISSUE TITLE
Assertion 'ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_NAMEDDATA || ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_NAMEDACCESSOR || ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_VIRTUAL' failed in ecma_is_property_configurable

### ISSUE THREAD

**Issue by renatahodovan** [jerryscript-project/jerryscript#1633]
###### Jerry version:

```
Checked revision: 92f74f3
Build: debug.linux
```
###### OS:

```
Ubuntu 16.04.2 LTS
```
###### Test case:

```javascript

delete new Uint16Array()[0]
```

###### Build command:
```
./tools/build.py --clean --debug --compile-flag=-m32 --system-allocator=on --jerry-libc=off
```

###### Backtrace:

```
ICE: Assertion 'ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_NAMEDDATA || ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_NAMEDACCESSOR || ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_VIRTUAL' failed at jerryscript/jerry-core/ecma/base/ecma-helpers.c(ecma_is_property_configurable):1197.
Error: ERR_FAILED_INTERNAL_ASSERTION
bt
#0  0xf7ffdbe9 in __kernel_vsyscall ()
#1  0x080f65c7 in raise ()
#2  0x080ba557 in abort ()
#3  0x08059ae5 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/targets/default/jerry-port-default-fatal.c:53
#4  0x0806fbd6 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:61
#5  0x0806fc09 in jerry_assert_fail (assertion=0x81468f8 "ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_NAMEDDATA || ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_NAMEDACCESSOR || ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_VI"..., file=0x814633c "jerryscript/jerry-core/ecma/base/ecma-helpers.c", function=0x812c584 <__func__.3897.lto_priv.138> "ecma_is_property_configurable", line=1197) at jerryscript/jerry-core/jrt/jrt-fatals.c:85
#6  0x080abe99 in ecma_is_property_configurable () at jerryscript/jerry-core/ecma/base/ecma-helpers.c:1195
#7  0x0806eb2d in ecma_op_general_object_delete (obj_p=0x8385938, property_name_p=0x8385978, is_throw=false) at jerryscript/jerry-core/ecma/operations/ecma-objects-general.c:164
#8  0x0807d76d in ecma_op_object_delete (obj_p=0x8385938, property_name_p=0x8385978, is_throw=false) at jerryscript/jerry-core/ecma/operations/ecma-objects.c:984
#9  0x080585de in vm_op_delete_prop (object=137910587, property=137910417, is_strict=false) at jerryscript/jerry-core/vm/opcodes.c:237
#10 0x0805c77b in vm_loop.lto_priv.239 (frame_ctx_p=0xffffc0c4) at jerryscript/jerry-core/vm/vm.c:1426
#11 0x08057d2c in vm_execute (frame_ctx_p=0xffffc0c4, arg_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:2642
#12 0x08057f0e in vm_run (bytecode_header_p=0x83858c0, this_binding_value=137909819, lex_env_p=0x83856e8, is_eval_code=false, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:2730
#13 0x0806104a in vm_run_global (bytecode_p=0x83858c0) at jerryscript/jerry-core/vm/vm.c:211
#14 0x080b29af in jerry_run (func_val=137910171) at jerryscript/jerry-core/jerry.c:385
#15 0x080b232b in main (argc=3, argv=0xffffc514) at jerryscript/jerry-main/main-unix.c:726
```

<sup>Found by  [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

**Comment by jiangzidong** [comment]
I will check it
