### ISSUE TITLE
heap-buffer-overflow in ecma_builtin_number_prototype_object_to_string

### ISSUE THREAD

**Issue by renatahodovan** [jerryscript-project/jerryscript#1634]
###### Jerry version:

```
Checked revision: 92f74f3
Build: debug.linux
```
###### OS:

```
Ubuntu 16.04.2 LTS, x86_64
```
###### Test case:

```javascript
65535.9.toString(3)
```

###### Build command:
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address --compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer --compile-flag=-fno-common --compile-flag=-g --jerry-libc=off --static-link=off --strip=off --system-allocator=on --linker-flag=-fuse-ld=gold
```

###### Backtrace:

```
==21706==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xf4501739 at pc 0xf7220fc8 bp 0xffcbeda8 sp 0xffcbe97c
READ of size 53 at 0xf4501739 thread T0
    #0 0xf7220fc7 in __asan_memmove (/usr/lib32/libasan.so.2+0x8afc7)
    #1 0xf72213df in __interceptor_memmove (/usr/lib32/libasan.so.2+0x8b3df)
    #2 0x80a2b3a in memmove /usr/include/bits/string3.h:59
    #3 0x80a2b3a in ecma_builtin_number_prototype_object_to_string.lto_priv.74 jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c:396
    #4 0x806aadb in ecma_builtin_number_prototype_object_to_locale_string jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c:432
    #5 0x806aadb in ecma_builtin_number_prototype_dispatch_routine jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.inc.h:39
    #6 0x8056cd6 in ecma_builtin_dispatch_routine jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.inc.h:91
    #7 0x8056cd6 in ecma_builtin_dispatch_call jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:844
    #8 0x8070325 in ecma_op_function_call jerryscript/jerry-core/ecma/operations/ecma-function-object.c:461
    #9 0x809124d in opfunc_call jerryscript/jerry-core/vm/vm.c:385
    #10 0x809124d in vm_execute.constprop.17 jerryscript/jerry-core/vm/vm.c:2651
    #11 0x809eb14 in vm_run jerryscript/jerry-core/vm/vm.c:2730
    #12 0x804a63e in vm_run_global jerryscript/jerry-core/vm/vm.c:211
    #13 0x804a63e in jerry_run jerryscript/jerry-core/jerry.c:385
    #14 0x804a63e in main jerryscript/jerry-main/main-unix.c:726
    #15 0xf6fdb636 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18636)
    #16 0x804af26  (jerryscript/build/bin/jerry+0x804af26)

0xf4501739 is located 0 bytes to the right of 57-byte region [0xf4501700,0xf4501739)
allocated by thread T0 here:
    #0 0xf722cdee in malloc (/usr/lib32/libasan.so.2+0x96dee)
    #1 0x807b50c in jmem_heap_alloc_block_internal jerryscript/jerry-core/jmem/jmem-heap.c:324
    #2 0x807b50c in jmem_heap_gc_and_alloc_block.lto_priv.40 jerryscript/jerry-core/jmem/jmem-heap.c:360
    #3 0x80a2625 in jmem_heap_alloc_block jerryscript/jerry-core/jmem/jmem-heap.c:406
    #4 0x80a2625 in ecma_builtin_number_prototype_object_to_string.lto_priv.74 jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c:298
    #5 0x806aadb in ecma_builtin_number_prototype_object_to_locale_string jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c:432
    #6 0x806aadb in ecma_builtin_number_prototype_dispatch_routine jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.inc.h:39
    #7 0x8056cd6 in ecma_builtin_dispatch_routine jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.inc.h:91
    #8 0x8056cd6 in ecma_builtin_dispatch_call jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:844
    #9 0x8070325 in ecma_op_function_call jerryscript/jerry-core/ecma/operations/ecma-function-object.c:461
    #10 0x809124d in opfunc_call jerryscript/jerry-core/vm/vm.c:385
    #11 0x809124d in vm_execute.constprop.17 jerryscript/jerry-core/vm/vm.c:2651
    #12 0x809eb14 in vm_run jerryscript/jerry-core/vm/vm.c:2730
    #13 0x804a63e in vm_run_global jerryscript/jerry-core/vm/vm.c:211
    #14 0x804a63e in jerry_run jerryscript/jerry-core/jerry.c:385
    #15 0x804a63e in main jerryscript/jerry-main/main-unix.c:726
    #16 0xf6fdb636 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18636)

SUMMARY: AddressSanitizer: heap-buffer-overflow ??:0 __asan_memmove
Shadow bytes around the buggy address:
  0x3e8a0290: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e8a02a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e8a02b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e8a02c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e8a02d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x3e8a02e0: 00 00 00 00 00 00 00[01]fa fa fa fa fd fd fd fd
  0x3e8a02f0: fd fd fd fd fa fa fa fa fd fd fd fd fd fd fd fd
  0x3e8a0300: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e8a0310: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e8a0320: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e8a0330: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==21706==ABORTING

```

Using a regular debug build (with `./tools/build.py --clean --debug` build command) we end up in an assertion failure:

```
ICE: Assertion 'next_offset == JMEM_HEAP_END_OF_LIST || jmem_is_heap_pointer (JMEM_HEAP_GET_ADDR_FROM_OFFSET (next_offset))' failed at jerryscript/jerry-core/jmem/jmem-heap.c(jmem_heap_alloc_block_internal):259.
Error: ERR_FAILED_INTERNAL_ASSERTION

Program received signal SIGABRT, Aborted.
0x000000000046e07c in syscall_2 () at jerryscript/jerry-libc/target/posix/jerry-asm.S:59
59    SYSCALL_2
(gdb) bt
#0  0x000000000046e07c in syscall_2 () at jerryscript/jerry-libc/target/posix/jerry-asm.S:59
#1  0x0000000000402760 in raise (sig=6) at jerryscript/jerry-libc/target/posix/jerry-libc-target.c:91
#2  0x0000000000402732 in abort () at jerryscript/jerry-libc/target/posix/jerry-libc-target.c:77
#3  0x00000000004113e9 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION)
    at jerryscript/targets/default/jerry-port-default-fatal.c:53
#4  0x000000000042c190 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:61
#5  0x000000000042c1e2 in jerry_assert_fail (
    assertion=0x475898 "next_offset == JMEM_HEAP_END_OF_LIST || jmem_is_heap_pointer (JMEM_HEAP_GET_ADDR_FROM_OFFSET (next_offset))", 
    file=0x475760 "jerryscript/jerry-core/jmem/jmem-heap.c", 
    function=0x484fa0 <__func__.3006.lto_priv.279> "jmem_heap_alloc_block_internal", line=259)
    at jerryscript/jerry-core/jrt/jrt-fatals.c:85
#6  0x000000000042b791 in jmem_heap_alloc_block_internal (size=62) at jerryscript/jerry-core/jmem/jmem-heap.c:258
#7  0x000000000042b914 in jmem_heap_gc_and_alloc_block (size=62, ret_null_on_error=false)
    at jerryscript/jerry-core/jmem/jmem-heap.c:360
#8  0x000000000042b9d5 in jmem_heap_alloc_block (size=62) at jerryscript/jerry-core/jmem/jmem-heap.c:406
#9  0x000000000045f21d in ecma_new_ecma_string_from_utf8 (string_p=0x692310 <jerry_global_heap+280> "10022220020.220022002200220022002210211012200000110221", 
    string_size=54) at jerryscript/jerry-core/ecma/base/ecma-helpers-string.c:190
#10 0x000000000043fd4a in ecma_builtin_number_prototype_object_to_string.lto_priv.367 (this_arg=153, arguments_list_p=0x7fffffffcb4c, arguments_list_len=1)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c:410
#11 0x000000000043f05f in ecma_builtin_number_prototype_dispatch_routine (builtin_routine_id=34, this_arg_value=153, arguments_list=0x7fffffffcb4c, 
    arguments_number=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.inc.h:37
#12 0x000000000045aa2f in ecma_builtin_dispatch_routine (builtin_object_id=ECMA_BUILTIN_ID_NUMBER_PROTOTYPE, builtin_routine_id=34, this_arg_value=153, 
    arguments_list=0x7fffffffcb4c, arguments_number=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.inc.h:91
#13 0x000000000045ae1a in ecma_builtin_dispatch_call (obj_p=0x6922c8 <jerry_global_heap+208>, this_arg_value=153, arguments_list_p=0x7fffffffcb4c, 
    arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:844
#14 0x000000000043771e in ecma_op_function_call (func_obj_p=0x6922c8 <jerry_global_heap+208>, this_arg_value=153, arguments_list_p=0x7fffffffcb4c, 
    arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:461
#15 0x000000000041dc0f in opfunc_call.lto_priv.138 (frame_ctx_p=0x7fffffffcb90) at jerryscript/jerry-core/vm/vm.c:385
#16 0x0000000000415681 in vm_execute (frame_ctx_p=0x7fffffffcb90, arg_p=0x0, arg_list_len=0)
    at jerryscript/jerry-core/vm/vm.c:2651
#17 0x00000000004158f5 in vm_run (bytecode_header_p=0x6923c8 <jerry_global_heap+464>, this_binding_value=27, lex_env_p=0x692220 <jerry_global_heap+40>, 
    is_eval_code=false, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:2730
#18 0x000000000041d89d in vm_run_global (bytecode_p=0x6923c8 <jerry_global_heap+464>) at jerryscript/jerry-core/vm/vm.c:211
#19 0x000000000046bc2e in jerry_run (func_val=139) at jerryscript/jerry-core/jerry.c:385
#20 0x000000000046b523 in main (argc=3, argv=0x7fffffffd1e8) at jerryscript/jerry-main/main-unix.c:726
```

<sup>Found by  [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

**Comment by zherczeg** [comment]
Duplicate of #742.
