### ISSUE TITLE
Assertion 'ecma_is_value_empty (completion_value)' failed in vm_var_decl

### ISSUE THREAD

**Issue by renatahodovan** [jerryscript-project/jerryscript#2105]
###### Jerry version:

```
Checked revision: 7692aa9d
Build command: ./tools/build.py --clean --debug
```
###### OS:

```
Ubuntu 17.10
```
###### Test case:

```javascript

Object.freeze (this)
{
eval('{ function boo() {} }')
}
```

###### Backtrace:

```
ICE: Assertion 'ecma_is_value_empty (completion_value)' failed at jerryscript/jerry-core/vm/opcodes.c(vm_var_decl):58.
Error: ERR_FAILED_INTERNAL_ASSERTION

Program received signal SIGABRT, Aborted.
0x0000000000475246 in syscall_2 () at jerryscript/jerry-libc/target/posix/jerry-asm.S:59
59	  SYSCALL_2
(gdb) bt
#0  0x0000000000475246 in syscall_2 () at jerryscript/jerry-libc/target/posix/jerry-asm.S:59
#1  0x000000000040ddfe in raise (sig=6) at jerryscript/jerry-libc/target/posix/jerry-libc-target.c:98
#2  0x000000000040ddd0 in abort () at jerryscript/jerry-libc/target/posix/jerry-libc-target.c:81
#3  0x0000000000407129 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION)
    at jerryscript/jerry-port/default/default-fatal.c:71
#4  0x000000000044dc48 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x000000000044dc9a in jerry_assert_fail (assertion=0x475538 "ecma_is_value_empty (completion_value)", 
    file=0x475508 "jerryscript/jerry-core/vm/opcodes.c", function=0x48afc8 <__func__.3502.lto_priv.46> "vm_var_decl", line=58)
    at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x0000000000401bc0 in vm_var_decl (frame_ctx_p=0x7fffffffd740, var_name_str_p=0x695a28 <jerry_global_heap+2024>)
    at jerryscript/jerry-core/vm/opcodes.c:58
#7  0x0000000000433630 in vm_init_loop (frame_ctx_p=0x7fffffffd740) at jerryscript/jerry-core/vm/vm.c:675
#8  0x0000000000437fcf in vm_execute (frame_ctx_p=0x7fffffffd740, arg_p=0x0, arg_list_len=0)
    at jerryscript/jerry-core/vm/vm.c:2791
#9  0x0000000000438289 in vm_run (bytecode_header_p=0x695a10 <jerry_global_heap+2000>, this_binding_value=27, 
    lex_env_p=0x695268 <jerry_global_heap+40>, is_eval_code=true, arg_list_p=0x0, arg_list_len=0)
    at jerryscript/jerry-core/vm/vm.c:2884
#10 0x0000000000432e4e in vm_run_eval (bytecode_data_p=0x695a10 <jerry_global_heap+2000>, is_direct=true)
    at jerryscript/jerry-core/vm/vm.c:277
#11 0x00000000004461ca in ecma_op_eval_chars_buffer (code_p=0x695420 <jerry_global_heap+480> "{ function boo() {} }", code_buffer_size=21, 
    is_direct=true, is_called_from_strict_mode_code=false) at jerryscript/jerry-core/ecma/operations/ecma-eval.c:103
#12 0x00000000004460b4 in ecma_op_eval (code_p=0x695418 <jerry_global_heap+472>, is_direct=true, is_called_from_strict_mode_code=false)
    at jerryscript/jerry-core/ecma/operations/ecma-eval.c:58
#13 0x0000000000422389 in ecma_builtin_global_object_eval (this_arg=72, x=474)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-global.c:87
#14 0x000000000042213a in ecma_builtin_global_dispatch_routine (builtin_routine_id=34, this_arg_value=72, arguments_list=0x7fffffffdb64, 
    arguments_number=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-global.inc.h:203
#15 0x0000000000473fe0 in ecma_builtin_dispatch_routine (builtin_object_id=ECMA_BUILTIN_ID_GLOBAL, builtin_routine_id=34, 
    this_arg_value=72, arguments_list=0x7fffffffdb64, arguments_number=1)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.inc.h:484
#16 0x000000000047416a in ecma_builtin_dispatch_call (obj_p=0x6956b8 <jerry_global_heap+1144>, this_arg_value=72, 
    arguments_list_p=0x7fffffffdb64, arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:844
#17 0x0000000000446a95 in ecma_op_function_call (func_obj_p=0x6956b8 <jerry_global_heap+1144>, this_arg_value=72, 
    arguments_list_p=0x7fffffffdb64, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:343
#18 0x0000000000433115 in opfunc_call (frame_ctx_p=0x7fffffffdbb0) at jerryscript/jerry-core/vm/vm.c:425
#19 0x0000000000438002 in vm_execute (frame_ctx_p=0x7fffffffdbb0, arg_p=0x0, arg_list_len=0)
    at jerryscript/jerry-core/vm/vm.c:2804
#20 0x0000000000438289 in vm_run (bytecode_header_p=0x695438 <jerry_global_heap+504>, this_binding_value=27, 
    lex_env_p=0x695268 <jerry_global_heap+40>, is_eval_code=false, arg_list_p=0x0, arg_list_len=0)
    at jerryscript/jerry-core/vm/vm.c:2884
#21 0x0000000000432d75 in vm_run_global (bytecode_p=0x695438 <jerry_global_heap+504>) at jerryscript/jerry-core/vm/vm.c:232
#22 0x00000000004598f1 in jerry_run (func_val=195) at jerryscript/jerry-core/api/jerry.c:558
#23 0x0000000000458400 in main (argc=3, argv=0x7fffffffded8) at jerryscript/jerry-main/main-unix.c:656
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by DanielBallaSZTE** [comment]
This issue can be closed now.
