### ISSUE TITLE
Assertion '((jmem_cpointer_t) uint_ptr) == uint_ptr' failed in jmem_decompress_pointer

### ISSUE THREAD

**Issue by renatahodovan** [jerryscript-project/jerryscript#2110]
###### Jerry version:

```
Checked revision: 7692aa9d
Build command: tools/build.py --clean --debug --profile=es2015-subset
```
###### OS:

```
Ubuntu 17.10
```
###### Test case:

```javascript
var arrowFn = () => {};
arrowFn.hasOwnProperty('caller');
```

###### Backtrace:

```
ICE: Assertion '((jmem_cpointer_t) uint_ptr) == uint_ptr' failed at jerryscript/jerry-core/jmem/jmem-allocator.c(jmem_decompress_pointer):100.
Error: ERR_FAILED_INTERNAL_ASSERTION

Program received signal SIGABRT, Aborted.
0x00000000004809d6 in syscall_2 () at jerryscript/jerry-libc/target/posix/jerry-asm.S:59
59	  SYSCALL_2
(gdb) bt
#0  0x00000000004809d6 in syscall_2 () at jerryscript/jerry-libc/target/posix/jerry-asm.S:59
#1  0x000000000040ca61 in raise (sig=6) at jerryscript/jerry-libc/target/posix/jerry-libc-target.c:98
#2  0x000000000040ca33 in abort () at jerryscript/jerry-libc/target/posix/jerry-libc-target.c:81
#3  0x0000000000405d8c in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION)
    at jerryscript/jerry-port/default/default-fatal.c:71
#4  0x000000000044371c in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x000000000044376e in jerry_assert_fail (assertion=0x4874a8 "((jmem_cpointer_t) uint_ptr) == uint_ptr", 
    file=0x487400 "jerryscript/jerry-core/jmem/jmem-allocator.c", 
    function=0x4944b0 <__func__.3201.lto_priv.432> "jmem_decompress_pointer", line=100)
    at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x0000000000442b4e in jmem_decompress_pointer (compressed_pointer=3670022)
    at jerryscript/jerry-core/jmem/jmem-allocator.c:100
#7  0x000000000045ab0d in ecma_op_function_try_to_lazy_instantiate_property (object_p=0x6a53e8 <jerry_global_heap+216>, 
    property_name_p=0x6a5500 <jerry_global_heap+496>) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:789
#8  0x000000000045dfe0 in ecma_op_object_get_own_property (object_p=0x6a53e8 <jerry_global_heap+216>, 
    property_name_p=0x6a5500 <jerry_global_heap+496>, property_ref_p=0x0, options=0)
    at jerryscript/jerry-core/ecma/operations/ecma-objects.c:243
#9  0x000000000045e2c8 in ecma_op_object_has_own_property (object_p=0x6a53e8 <jerry_global_heap+216>, 
    property_name_p=0x6a5500 <jerry_global_heap+496>) at jerryscript/jerry-core/ecma/operations/ecma-objects.c:362
#10 0x0000000000428053 in ecma_builtin_object_prototype_object_has_own_property (this_arg=219, arg=498)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-object-prototype.c:153
#11 0x0000000000427d19 in ecma_builtin_object_prototype_dispatch_routine (builtin_routine_id=61, this_arg_value=219, 
    arguments_list=0x7fffffffdb1c, arguments_number=1)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-object-prototype.inc.h:35
#12 0x0000000000453b83 in ecma_builtin_dispatch_routine (builtin_object_id=ECMA_BUILTIN_ID_OBJECT_PROTOTYPE, builtin_routine_id=61, 
    this_arg_value=219, arguments_list=0x7fffffffdb1c, arguments_number=1)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.inc.h:20
#13 0x00000000004542ce in ecma_builtin_dispatch_call (obj_p=0x6a53f8 <jerry_global_heap+232>, this_arg_value=219, 
    arguments_list_p=0x7fffffffdb1c, arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:844
#14 0x0000000000459db6 in ecma_op_function_call (func_obj_p=0x6a53f8 <jerry_global_heap+232>, this_arg_value=219, 
    arguments_list_p=0x7fffffffdb1c, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:343
#15 0x000000000044d740 in opfunc_call (frame_ctx_p=0x7fffffffdb60) at jerryscript/jerry-core/vm/vm.c:425
#16 0x000000000045262d in vm_execute (frame_ctx_p=0x7fffffffdb60, arg_p=0x0, arg_list_len=0)
    at jerryscript/jerry-core/vm/vm.c:2804
#17 0x00000000004528b4 in vm_run (bytecode_header_p=0x6a5520 <jerry_global_heap+528>, this_binding_value=27, 
    lex_env_p=0x6a5340 <jerry_global_heap+48>, is_eval_code=false, arg_list_p=0x0, arg_list_len=0)
    at jerryscript/jerry-core/vm/vm.c:2884
#18 0x000000000044d368 in vm_run_global (bytecode_p=0x6a5520 <jerry_global_heap+528>) at jerryscript/jerry-core/vm/vm.c:232
#19 0x0000000000465b61 in jerry_run (func_val=203) at jerryscript/jerry-core/api/jerry.c:558
#20 0x0000000000464670 in main (argc=3, argv=0x7fffffffde88) at jerryscript/jerry-main/main-unix.c:656
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by DanielBallaSZTE** [comment]
I think we can close this issue now.
