### ISSUE TITLE
 Assertion 'qmin <= qmax' failed in re_insert_simple_iterator

### ISSUE THREAD

**Issue by renatahodovan** [jerryscript-project/jerryscript#2204]
###### Jerry version:

```
Checked revision: d7991ae5
Build command: ./tools/build.py --clean --debug
```
###### OS:

```
Ubuntu 17.10
```
###### Test case:

```javascript
new RegExp("\{{91406,456}");
```

###### Backtrace:

```
ICE: Assertion 'qmin <= qmax' failed at jerryscript/jerry-core/parser/regexp/re-compiler.c(re_insert_simple_iterator):66.
Error: ERR_FAILED_INTERNAL_ASSERTION

Program received signal SIGABRT, Aborted.
0x000000000046dec6 in syscall_2 () at jerryscript/jerry-libc/target/posix/jerry-asm.S:59
59	  SYSCALL_2
(gdb) bt
#0  0x000000000046dec6 in syscall_2 () at jerryscript/jerry-libc/target/posix/jerry-asm.S:59
#1  0x000000000040ccc0 in raise (sig=6) at jerryscript/jerry-libc/target/posix/jerry-libc-target.c:98
#2  0x000000000040cc92 in abort () at jerryscript/jerry-libc/target/posix/jerry-libc-target.c:81
#3  0x0000000000405feb in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION)
    at jerryscript/jerry-port/default/default-fatal.c:71
#4  0x0000000000450c2c in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x0000000000450c7e in jerry_assert_fail (assertion=0x4758b9 "qmin <= qmax", 
    file=0x474ce8 "jerryscript/jerry-core/parser/regexp/re-compiler.c", 
    function=0x47fb70 <__func__.3838.lto_priv.330> "re_insert_simple_iterator", line=66)
    at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x0000000000438b92 in re_insert_simple_iterator (re_ctx_p=0x7fffffffd720, new_atom_start_offset=1)
    at jerryscript/jerry-core/parser/regexp/re-compiler.c:66
#7  0x0000000000439177 in re_parse_alternative (re_ctx_p=0x7fffffffd720, expect_eof=true)
    at jerryscript/jerry-core/parser/regexp/re-compiler.c:276
#8  0x00000000004399ad in re_compile_bytecode (out_bytecode_p=0x7fffffffd7a0, pattern_str_p=0x68e448 <jerry_global_heap+520>, flags=0)
    at jerryscript/jerry-core/parser/regexp/re-compiler.c:560
#9  0x00000000004132b4 in ecma_op_create_regexp_object (pattern_p=0x68e448 <jerry_global_heap+520>, flags_str_p=0x0)
    at jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:292
#10 0x00000000004320f4 in ecma_builtin_regexp_dispatch_construct (arguments_list_p=0x7fffffffd9c4, arguments_list_len=1)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-regexp.c:136
#11 0x0000000000447092 in ecma_builtin_dispatch_construct (obj_p=0x68e310 <jerry_global_heap+208>, arguments_list_p=0x7fffffffd9c4, 
    arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.inc.h:171
#12 0x000000000044a448 in ecma_op_function_construct (func_obj_p=0x68e310 <jerry_global_heap+208>, arguments_list_p=0x7fffffffd9c4, 
    arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:648
#13 0x000000000043bb8d in opfunc_construct (frame_ctx_p=0x7fffffffda00) at jerryscript/jerry-core/vm/vm.c:483
#14 0x0000000000440ab9 in vm_execute (frame_ctx_p=0x7fffffffda00, arg_p=0x0, arg_list_len=0)
    at jerryscript/jerry-core/vm/vm.c:2876
#15 0x0000000000440cfe in vm_run (bytecode_header_p=0x68e468 <jerry_global_heap+552>, this_binding_value=27, 
    lex_env_p=0x68e268 <jerry_global_heap+40>, is_eval_code=false, arg_list_p=0x0, arg_list_len=0)
    at jerryscript/jerry-core/vm/vm.c:2951
#16 0x000000000043b6e0 in vm_run_global (bytecode_p=0x68e468 <jerry_global_heap+552>)
    at jerryscript/jerry-core/vm/vm.c:232
#17 0x0000000000453dbc in jerry_run (func_val=195) at jerryscript/jerry-core/api/jerry.c:561
#18 0x0000000000452964 in main (argc=3, argv=0x7fffffffdd28) at jerryscript/jerry-main/main-unix.c:611
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by LaszloLango** [comment]
I'm working on this.
