### ISSUE TITLE
Assertion '(literal_p->status_flags & ~(LEXER_FLAG_SOURCE_PTR | LEXER_FLAG_LATE_INIT)) == 0' failed in parser_compute_indicies

### ISSUE THREAD

**Issue by renatahodovan** [jerryscript-project/jerryscript#2656]
###### Jerry version:

```
Checked revision: ec142f5f
Build command: ./tools/build.py --clean --debug --profile=es2015-subset --logging=on
```

###### OS:

```
Ubuntu 18.04, x86_64
```

###### Test case:

```javascript
function testcase ( ) { 
    obj.hasOwnProperty("arguments") ; 
} 
```

###### Backtrace:

```
ICE: Assertion '(literal_p->status_flags & ~(LEXER_FLAG_SOURCE_PTR | LEXER_FLAG_LATE_INIT)) == 0' failed at jerryscript/jerry-core/parser/js/js-parser.c(parser_compute_indicies):363.
Error: ERR_FAILED_INTERNAL_ASSERTION

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7a24801 in __GI_abort () at abort.c:79
#2  0x000055555555f2f6 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:71
#3  0x000055555558b684 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:63
#4  0x000055555558b6d6 in jerry_assert_fail (assertion=0x5555555dece8 "(literal_p->status_flags & ~(LEXER_FLAG_SOURCE_PTR | LEXER_FLAG_LATE_INIT)) == 0", 
    file=0x5555555deca0 "jerryscript/jerry-core/parser/js/js-parser.c", function=0x5555555d5070 <__func__.5115.lto_priv.396> "parser_compute_indicies", line=363)
    at jerryscript/jerry-core/jrt/jrt-fatals.c:87
#5  0x000055555558ecd5 in parser_compute_indicies (context_p=0x7fffffffdab0, ident_end=0x7fffffffd720, uninitialized_var_end=0x7fffffffd71e, initialized_var_end=0x7fffffffd71c, 
    const_literal_end=0x7fffffffd71a) at jerryscript/jerry-core/parser/js/js-parser.c:363
#6  0x000055555558fed6 in parser_post_processing (context_p=0x7fffffffdab0) at jerryscript/jerry-core/parser/js/js-parser.c:1489
#7  0x0000555555592103 in parser_parse_function (context_p=0x7fffffffdab0, status_flags=6) at jerryscript/jerry-core/parser/js/js-parser.c:2640
#8  0x000055555556f684 in lexer_construct_function_object (context_p=0x7fffffffdab0, extra_status_flags=6) at jerryscript/jerry-core/parser/js/js-lexer.c:1992
#9  0x000055555557655d in parser_parse_function_statement.lto_priv.174 (context_p=0x7fffffffdab0) at jerryscript/jerry-core/parser/js/js-parser-statm.c:438
#10 0x000055555555a0b9 in parser_parse_statements (context_p=0x7fffffffdab0) at jerryscript/jerry-core/parser/js/js-parser-statm.c:1894
#11 0x00005555555919a5 in parser_parse_source (arg_list_p=0x0, arg_list_size=0, source_p=0x5555557f6100 <buffer.lto_priv> "function testcase ( ) { \n    obj.hasOwnProperty(\"arguments\") ; \n} \n", 
    source_size=67, parse_opts=0, error_location_p=0x7fffffffdcc4) at jerryscript/jerry-core/parser/js/js-parser.c:2397
#12 0x0000555555592637 in parser_parse_script (arg_list_p=0x0, arg_list_size=0, source_p=0x5555557f6100 <buffer.lto_priv> "function testcase ( ) { \n    obj.hasOwnProperty(\"arguments\") ; \n} \n", 
    source_size=67, parse_opts=0, bytecode_data_p=0x7fffffffdd10) at jerryscript/jerry-core/parser/js/js-parser.c:2848
#13 0x00005555555c22c9 in jerry_parse (resource_name_p=0x7fffffffe383 "test.js", resource_name_length=7, 
    source_p=0x5555557f6100 <buffer.lto_priv> "function testcase ( ) { \n    obj.hasOwnProperty(\"arguments\") ; \n} \n", source_size=67, parse_opts=0)
    at jerryscript/jerry-core/api/jerry.c:401
#14 0x00005555555c0e6b in main (argc=3, argv=0x7fffffffe038) at jerryscript/jerry-main/main-unix.c:667
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by rerobika** [comment]
Note: the issue is valid with the default `5.1` profile as well.
