### ISSUE TITLE
Assertion byte_code_start_p[-1] == CBC_EXT_PUSH_SUPER || byte_code_start_p[-1] == CBC_EXT_PUSH_CONSTRUCTOR_SUPER_PROP in vm_loop

### ISSUE THREAD

**Issue by renatahodovan** [jerryscript-project/jerryscript#3067]
###### JerryScript revision
086c4ebf

###### Build platform
Linux-4.15.0-54-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### Test case
```javascript
function f ( ) { }

var B = class extends f {
    constructor ( ) {
        super(0)
        super.$
        this.$= $
    }
}

C = class extends B {
    g ( ) {
        return function ( ) { }
    }
}

D = class extends C {
    constructor ( ) { super ( ) }
    g ( ) { }
}

new D
```

###### Output
```text
ICE: Assertion 'byte_code_start_p[-1] == CBC_EXT_PUSH_SUPER || byte_code_start_p[-1] == CBC_EXT_PUSH_CONSTRUCTOR_SUPER_PROP' failed at jerryscript/jerry-core/vm/vm.c(vm_loop):1621.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

###### Backtrace
```text
bt
#0  0xf7fd5059 in __kernel_vsyscall ()
#1  0xf77fc832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77fdcc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5657ae47 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:71
#4  0x56617934 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x56617975 in jerry_assert_fail (assertion=0x566a6940 "byte_code_start_p[-1] == CBC_EXT_PUSH_SUPER || byte_code_start_p[-1] == CBC_EXT_PUSH_CONSTRUCTOR_SUPER_PROP", file=0x566a5ee0 "jerryscript/jerry-core/vm/vm.c", function=0x566862c0 <__func__.5931.lto_priv.427> "vm_loop", line=1621) at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x565ee089 in vm_loop (frame_ctx_p=0xffffc160) at jerryscript/jerry-core/vm/vm.c:1620
#7  0x565f9958 in vm_execute (frame_ctx_p=0xffffc160, arg_p=0xffffc434, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3616
#8  0x565fa2bc in vm_run (bytecode_header_p=0xf5103dc0, this_binding_value=4124050355, lex_env_p=0xf5d00370, parse_opts=0, arg_list_p=0xffffc434, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3742
#9  0x56633d9d in ecma_op_function_call (func_obj_p=0xf5f00520, this_arg_value=4124050355, arguments_list_p=0xffffc434, arguments_list_len=0) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:807
#10 0x56634a20 in ecma_op_function_construct (func_obj_p=0xf5f00520, this_arg_value=4124050355, arguments_list_p=0xffffc435, arguments_list_len=0) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1134
#11 0x565e81d7 in vm_super_call (frame_ctx_p=0xffffc4a0) at jerryscript/jerry-core/vm/vm.c:495
#12 0x565f99c8 in vm_execute (frame_ctx_p=0xffffc4a0, arg_p=0xffffc764, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3628
#13 0x565fa2bc in vm_run (bytecode_header_p=0xf4f00e90, this_binding_value=4124050355, lex_env_p=0xf5d00390, parse_opts=0, arg_list_p=0xffffc764, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3742
#14 0x56633d9d in ecma_op_function_call (func_obj_p=0xf5f00340, this_arg_value=4124050355, arguments_list_p=0xffffc764, arguments_list_len=0) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:807
#15 0x56634a20 in ecma_op_function_construct (func_obj_p=0xf5f00340, this_arg_value=4124050355, arguments_list_p=0xffffc765, arguments_list_len=0) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1134
#16 0x565e8cfd in opfunc_construct (frame_ctx_p=0xffffc7e0) at jerryscript/jerry-core/vm/vm.c:665
#17 0x565f99d8 in vm_execute (frame_ctx_p=0xffffc7e0, arg_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3634
#18 0x565fa2bc in vm_run (bytecode_header_p=0xf5103c40, this_binding_value=4126149459, lex_env_p=0xf5d007b0, parse_opts=0, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3742
#19 0x565e7a1c in vm_run_global (bytecode_p=0xf5103c40) at jerryscript/jerry-core/vm/vm.c:282
#20 0x5664170c in jerry_run (func_val=4126148259) at jerryscript/jerry-core/api/jerry.c:570
#21 0x5663e070 in main (argc=3, argv=0xffffcc14) at jerryscript/jerry-main/main-unix.c:743
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by rerobika** [comment]
Fixed via #3077 .
