### ISSUE TITLE
Assertion entry_index <= mask failed in ecma_property_hashmap_create

### ISSUE THREAD

**Issue by YaoHouyou** [jerryscript-project/jerryscript#3216]
###### JerryScript revision
[84a56ef](https://github.com/jerryscript-project/jerryscript/commit/84a56efd4fc64ae33a11f657d21b2eaa966e8d4b)

###### Build platform
`Ubuntu 18.04.2 LTS (Linux 4.18.0-20-generic x86_64)`

###### Build steps
```
python ./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset \
--line-info=on --cpointer-32bit=on --mem-heap=1572864
```

###### Test case
```
var NISLFuzzingFunc = function(size) {
    var array = new Array(size);
    print(array.length);
    while (size--){
        array[size] = 0;
    }
};
var NISLParameter0 = 165537;
NISLFuzzingFunc(NISLParameter0);
```

###### Execution steps
```
./jerryscript/build/bin/jerry testcase.js
```

###### Output
```
165537
ICE: Assertion 'entry_index <= mask' failed at jerryscript/jerry-core/ecma/base/ecma-property-hashmap.c(ecma_property_hashmap_create):185.
Error: ERR_FAILED_INTERNAL_ASSERTION
Aborted (core dumped)
```

###### Backtrace
```
#0  0xf7fd5059 in __kernel_vsyscall ()
#1  0xf7820452 in raise () from /lib32/libc.so.6
#2  0xf7821871 in abort () from /lib32/libc.so.6
#3  0x56579ce5 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION)
    at jerryscript/jerry-port/default/default-fatal.c:30
#4  0x5661568d in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION)
    at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x566156ce in jerry_assert_fail (assertion=0x566c8c40 "entry_index <= mask", 
    file=0x566c8b60 "jerryscript/jerry-core/ecma/base/ecma-property-hashmap.c", 
    function=0x56686800 <__func__.5304.lto_priv.665> "ecma_property_hashmap_create", line=185)
    at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x5665e8d8 in ecma_property_hashmap_create (object_p=0xf5f007c0)
    at jerryscript/jerry-core/ecma/base/ecma-property-hashmap.c:185
#7  0x5665ee84 in ecma_property_hashmap_insert (object_p=0xf5f007c0, name_p=0x34d3f5, property_pair_p=0xf4190310, property_index=0)
    at jerryscript/jerry-core/ecma/base/ecma-property-hashmap.c:262
#8  0x56658393 in ecma_create_property (object_p=0xf5f007c0, name_p=0x34d3f5, type_and_flags=29 '\035', value=..., out_prop_p=0x0)
    at jerryscript/jerry-core/ecma/base/ecma-helpers.c:389
#9  0x56658ac3 in ecma_create_named_data_property (object_p=0xf5f007c0, name_p=0x34d3f5, prop_attributes=28 '\034', out_prop_p=0x0)
    at jerryscript/jerry-core/ecma/base/ecma-helpers.c:486
#10 0x56604c26 in ecma_op_object_put (object_p=0xf5f007c0, property_name_p=0x34d3f5, value=0, is_throw=false)
    at jerryscript/jerry-core/ecma/operations/ecma-objects.c:1269
#11 0x565e5c12 in vm_op_set_value (object=4126148547, property=1731056, value=0, is_strict=false)
    at jerryscript/jerry-core/vm/vm.c:212
#12 0x565f6779 in vm_loop (frame_ctx_p=0xffffc710) at jerryscript/jerry-core/vm/vm.c:3363
#13 0x565f80e5 in vm_execute (frame_ctx_p=0xffffc710, arg_p=0xffffc964, arg_list_len=1)
    at jerryscript/jerry-core/vm/vm.c:3630
#14 0x565f8abf in vm_run (bytecode_header_p=0xf5301ad0, this_binding_value=4126149459, lex_env_p=0xf5d007b0, parse_opts=0, arg_list_p=0xffffc964, arg_list_len=1)
    at jerryscript/jerry-core/vm/vm.c:3756
#15 0x5663e57f in ecma_op_function_call (func_obj_p=0xf5f00850, this_arg_value=72, arguments_list_p=0xffffc964, arguments_list_len=1)
    at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:807
#16 0x565e6a43 in opfunc_call (frame_ctx_p=0xffffc9d0) at jerryscript/jerry-core/vm/vm.c:581
#17 0x565f8145 in vm_execute (frame_ctx_p=0xffffc9d0, arg_p=0x0, arg_list_len=0)
    at jerryscript/jerry-core/vm/vm.c:3636
#18 0x565f8abf in vm_run (bytecode_header_p=0xf6301520, this_binding_value=4126149459, lex_env_p=0xf5d007b0, parse_opts=0, arg_list_p=0x0, arg_list_len=0)
    at jerryscript/jerry-core/vm/vm.c:3756
#19 0x565e5cda in vm_run_global (bytecode_p=0xf6301520) at jerryscript/jerry-core/vm/vm.c:282
#20 0x5666e0a8 in jerry_run (func_val=4126148787) at jerryscript/jerry-core/api/jerry.c:576
#21 0x5666a8b0 in main (argc=2, argv=0xffffce04) at jerryscript/jerry-main/main-unix.c:735
```

**Comment by ossy-szeged** [comment]
I bisected this issue and turned out that #3032 caused this bug.
