### ISSUE TITLE
Assertion scope_stack_p >= context_p->scope_stack_p in parser_parse_function_statement

### ISSUE THREAD

**Issue by renatahodovan** [jerryscript-project/jerryscript#3434]
###### JerryScript revision
b8bc013f

###### Build platform
Linux-4.15.0-72-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### Test case
```javascript
function g({
    ["y"]: {
        get = 5
    }
}) {}

function h
```

###### Output
```text
ICE: Assertion 'scope_stack_p >= context_p->scope_stack_p' failed at jerryscript/jerry-core/parser/js/js-parser-statm.c(parser_parse_function_statement):713.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

###### Backtrace
```text
bt
#0  0xf7fd5079 in __kernel_vsyscall ()
#1  0xf77fc832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77fdcc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5657b698 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:30
#4  0x56647006 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x56647047 in jerry_assert_fail (assertion=0x566d2600 "scope_stack_p >= context_p->scope_stack_p", file=0x566d2080 "jerryscript/jerry-core/parser/js/js-parser-statm.c", function=0x566c1860 <__func__.5627.lto_priv.237> "parser_parse_function_statement", line=713) at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x565aecf9 in parser_parse_function_statement.lto_priv.225 (context_p=0xffffc4b0) at jerryscript/jerry-core/parser/js/js-parser-statm.c:713
#7  0x5657133b in parser_parse_statements (context_p=0xffffc4b0) at jerryscript/jerry-core/parser/js/js-parser-statm.c:2722
#8  0x56607000 in parser_parse_source (arg_list_p=0x0, arg_list_size=0, source_p=0x56725ac0 <buffer.lto_priv> "String ( ( function ( [ a ] , b , { c } ) { } ) .length === 3 ) ; \nfunction f ( [ a = \"x\" , b = \"y\" , c = \"z\" ] ) { String ( a === \"a\" ) ; \nString ( b === \"b\" ) ; \nString ( c === \"z\" ) ; \n} \nf ( \"ab\" "..., source_size=1084, parse_opts=0, error_location_p=0xffffc6c0) at jerryscript/jerry-core/parser/js/js-parser.c:2026
#9  0x5660a398 in parser_parse_script (arg_list_p=0x0, arg_list_size=0, source_p=0x56725ac0 <buffer.lto_priv> "String ( ( function ( [ a ] , b , { c } ) { } ) .length === 3 ) ; \nfunction f ( [ a = \"x\" , b = \"y\" , c = \"z\" ] ) { String ( a === \"a\" ) ; \nString ( b === \"b\" ) ; \nString ( c === \"z\" ) ; \n} \nf ( \"ab\" "..., source_size=1084, parse_opts=0, bytecode_data_p=0xffffc780) at jerryscript/jerry-core/parser/js/js-parser.c:2519
#10 0x56696783 in jerry_parse (resource_name_p=0xffffcd8d "/home/reni/.fuzzinator_42037//jerryscript/picireny/244016613766980252626867290749981980902.js", resource_name_length=93, source_p=0x56725ac0 <buffer.lto_priv> "String ( ( function ( [ a ] , b , { c } ) { } ) .length === 3 ) ; \nfunction f ( [ a = \"x\" , b = \"y\" , c = \"z\" ] ) { String ( a === \"a\" ) ; \nString ( b === \"b\" ) ; \nString ( c === \"z\" ) ; \n} \nf ( \"ab\" "..., source_size=1084, parse_opts=0) at jerryscript/jerry-core/api/jerry.c:445
#11 0x56693507 in main (argc=2, argv=0xffffcb14) at jerryscript/jerry-main/main-unix.c:731
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by ossy-szeged** [comment]
It started to assert since 8bdb32cc8871000ba1db1269f2a5f7b4698e2351
"Implement function destructuring argument support. (#3322)"
