### ISSUE TITLE
Assertion ecma_op_object_is_fast_array (object_p) in ecma_fast_array_extend

### ISSUE THREAD

**Issue by renatahodovan** [jerryscript-project/jerryscript#3459]
###### JerryScript revision
d0b4e7dd

###### Build platform
Linux-4.15.0-72-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### Test case
```javascript
class MyOtherArray {}

class MyNonArray extends Array {
  static [Symbol.species] () {}
}

(() => MyNonArray)().prototype.slice.call(new MyNonArray((0) === 1))
```

###### Output
```text
ICE: Assertion 'ecma_op_object_is_fast_array (object_p)' failed at jerryscript/jerry-core/ecma/operations/ecma-array-object.c(ecma_fast_array_extend):313.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

###### Backtrace
```text
bt
#0  0xf7fd5079 in __kernel_vsyscall ()
#1  0xf77fc832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77fdcc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5657b7cd in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:30
#4  0x5664976b in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x566497ac in jerry_assert_fail (assertion=0x566ea3e0 "ecma_op_object_is_fast_array (object_p)", file=0x566ea280 "jerryscript/jerry-core/ecma/operations/ecma-array-object.c", function=0x566b24e0 <__func__.5014.lto_priv.98> "ecma_fast_array_extend", line=313) at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x56656d9b in ecma_fast_array_extend (object_p=0xf5d00a10, new_length=1) at jerryscript/jerry-core/ecma/operations/ecma-array-object.c:313
#7  0x565f0265 in ecma_builtin_array_prototype_object_slice (arg1=72, arg2=72, obj_p=0xf5f01cf0, len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c:857
#8  0x565f59a7 in ecma_builtin_array_prototype_dispatch_routine (builtin_routine_id=85, this_arg=4126153971, arguments_list_p=0xffffc1c0, arguments_number=0) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c:2625
#9  0x56692f8b in ecma_builtin_dispatch_routine (builtin_object_id=ECMA_BUILTIN_ID_ARRAY_PROTOTYPE, builtin_routine_id=85, this_arg_value=4126153971, arguments_list_p=0xffffc1c0, arguments_list_len=0) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1020
#10 0x566931ec in ecma_builtin_dispatch_call (obj_p=0xf5f01150, this_arg_value=4126153971, arguments_list_p=0xffffc424, arguments_list_len=0) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1045
#11 0x56665786 in ecma_op_function_call (func_obj_p=0xf5f01150, this_arg_value=4126153971, arguments_list_p=0xffffc424, arguments_list_len=0) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:773
#12 0x565b8ec8 in ecma_builtin_function_prototype_object_call (func_obj_p=0xf5f01150, arguments_list_p=0xffffc420, arguments_number=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.c:190
#13 0x565b9460 in ecma_builtin_function_prototype_dispatch_routine (builtin_routine_id=78, this_arg=4126150995, arguments_list_p=0xffffc420, arguments_number=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.c:337
#14 0x56692f8b in ecma_builtin_dispatch_routine (builtin_object_id=ECMA_BUILTIN_ID_FUNCTION_PROTOTYPE, builtin_routine_id=78, this_arg_value=4126150995, arguments_list_p=0xffffc420, arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1020
#15 0x566931ec in ecma_builtin_dispatch_call (obj_p=0xf5f020e0, this_arg_value=4126150995, arguments_list_p=0xffffc6ec, arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1045
#16 0x56665786 in ecma_op_function_call (func_obj_p=0xf5f020e0, this_arg_value=4126150995, arguments_list_p=0xffffc6ec, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:773
#17 0x5662e71b in opfunc_call.lto_priv.461 (frame_ctx_p=0xffffc690) at jerryscript/jerry-core/vm/vm.c:699
#18 0x565e2a47 in vm_execute (frame_ctx_p=0xffffc690) at jerryscript/jerry-core/vm/vm.c:4076
#19 0x565e3063 in vm_run (bytecode_header_p=0xf4d03780, this_binding_value=4126149459, lex_env_p=0xf5d007b0, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:4199
#20 0x5662d02e in vm_run_global (bytecode_p=0xf4d03780) at jerryscript/jerry-core/vm/vm.c:286
#21 0x5669ab1f in jerry_run (func_val=4126146579) at jerryscript/jerry-core/api/jerry.c:595
#22 0x5669728c in main (argc=2, argv=0xffffcb14) at jerryscript/jerry-main/main-unix.c:740
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by ossy-szeged** [comment]
note: this test asserts since e0d8c4ca103384a046bc90bb68a45e7d99d91b7b
"Add @@species accessor to Array and Promise builtin objects (#3440)"
