### ISSUE TITLE
Assertion (literal_p->status_flags & ~(LEXER_FLAG_SOURCE_PTR | LEXER_FLAG_LATE_INIT)) == 0 in parser_compute_indicies

### ISSUE THREAD

**Issue by renatahodovan** [jerryscript-project/jerryscript#3527]
###### JerryScript revision
71d4e121

###### Build platform
Linux-4.15.0-72-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### Test case
```javascript
function $({
    $: {
        [$.$]
    }
}) {}
```

###### Output
```text
ICE: Assertion '(literal_p->status_flags & ~(LEXER_FLAG_SOURCE_PTR | LEXER_FLAG_LATE_INIT)) == 0' failed at jerryscript/jerry-core/parser/js/js-parser.c(parser_compute_indicies):166.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

###### Backtrace
```text
bt
#0  0xf7fd5079 in __kernel_vsyscall ()
#1  0xf77fc832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77fdcc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5657d197 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:30
#4  0x566504cd in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x5665050e in jerry_assert_fail (assertion=0x566e9340 "(literal_p->status_flags & ~(LEXER_FLAG_SOURCE_PTR | LEXER_FLAG_LATE_INIT)) == 0", file=0x566e9260 "jerryscript/jerry-core/parser/js/js-parser.c", function=0x566c4960 <__func__.5597.lto_priv.41> "parser_compute_indicies", line=166) at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x5660385f in parser_compute_indicies (context_p=0xffffc490, ident_end=0xffffbe20, const_literal_end=0xffffbde0) at jerryscript/jerry-core/parser/js/js-parser.c:166
#7  0x56605161 in parser_post_processing (context_p=0xffffc490) at jerryscript/jerry-core/parser/js/js-parser.c:949
#8  0x5660e6b9 in parser_parse_function (context_p=0xffffc490, status_flags=6) at jerryscript/jerry-core/parser/js/js-parser.c:2416
#9  0x565b0242 in parser_parse_function_statement.lto_priv.223 (context_p=0xffffc490) at jerryscript/jerry-core/parser/js/js-parser-statm.c:719
#10 0x565701e5 in parser_parse_statements (context_p=0xffffc490) at jerryscript/jerry-core/parser/js/js-parser-statm.c:2774
#11 0x5660bcfe in parser_parse_source (arg_list_p=0x0, arg_list_size=0, source_p=0x56734560 <buffer.lto_priv> "function g ( { [ \"y\" ] : { [ Symbol .toPrimitive ] = 5 } } ) { } \n ", source_size=67, parse_opts=0, error_location_p=0xffffc6a0) at jerryscript/jerry-core/parser/js/js-parser.c:2116
#12 0x5660f341 in parser_parse_script (arg_list_p=0x0, arg_list_size=0, source_p=0x56734560 <buffer.lto_priv> "function g ( { [ \"y\" ] : { [ Symbol .toPrimitive ] = 5 } } ) { } \n ", source_size=67, parse_opts=0, bytecode_data_p=0xffffc760) at jerryscript/jerry-core/parser/js/js-parser.c:2639
#13 0x566a134c in jerry_parse (resource_name_p=0xffffcd7d "/home/reni/.fuzzinator_31942//jerryscript/picireny/63327936987741173392446431556505935214.js", resource_name_length=92, source_p=0x56734560 <buffer.lto_priv> "function g ( { [ \"y\" ] : { [ Symbol .toPrimitive ] = 5 } } ) { } \n ", source_size=67, parse_opts=0) at jerryscript/jerry-core/api/jerry.c:445
#14 0x5669dfc4 in main (argc=2, argv=0xffffcb04) at jerryscript/jerry-main/main-unix.c:741
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by renatahodovan** [comment]
After some deletion another assertion failure can be triggered:

```js
function $({
    $: {
        [$]
    }
}) {}
```

###### Output
```text
ICE: Assertion 'context.status_flags & PARSER_SCANNING_SUCCESSFUL' failed at jerryscript/jerry-core/parser/js/js-parser.c(parser_parse_source):2143.
Error: ERR_FAILED_INTERNAL_ASSERTION
```



###### Backtrace
```text
bt
#0  0xf7fd5079 in __kernel_vsyscall ()
#1  0xf77fc832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77fdcc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5657d197 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:30
#4  0x566504cd in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x5665050e in jerry_assert_fail (assertion=0x566e9fc0 "context.status_flags & PARSER_SCANNING_SUCCESSFUL", file=0x566e9260 "jerryscript/jerry-core/parser/js/js-parser.c", function=0x566c4ae0 <__func__.5800.lto_priv.517> "parser_parse_source", line=2143) at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x5660c29a in parser_parse_source (arg_list_p=0x0, arg_list_size=0, source_p=0x56734560 <buffer.lto_priv> "function\t$(\t{\t$:\t{\t[\t$\t]\t}\t}\t)\t{\t}\t\r\t", source_size=37, parse_opts=0, error_location_p=0xffffc6a0) at jerryscript/jerry-core/parser/js/js-parser.c:2143
#7  0x5660f341 in parser_parse_script (arg_list_p=0x0, arg_list_size=0, source_p=0x56734560 <buffer.lto_priv> "function\t$(\t{\t$:\t{\t[\t$\t]\t}\t}\t)\t{\t}\t\r\t", source_size=37, parse_opts=0, bytecode_data_p=0xffffc760) at jerryscript/jerry-core/parser/js/js-parser.c:2639
#8  0x566a134c in jerry_parse (resource_name_p=0xffffcd7d "/home/reni/.fuzzinator_31942//jerryscript/picireny/63327936987741173392446431556505935214.js", resource_name_length=92, source_p=0x56734560 <buffer.lto_priv> "function\t$(\t{\t$:\t{\t[\t$\t]\t}\t}\t)\t{\t}\t\r\t", source_size=37, parse_opts=0) at jerryscript/jerry-core/api/jerry.c:445
#9  0x5669dfc4 in main (argc=2, argv=0xffffcb04) at jerryscript/jerry-main/main-unix.c:741
```
