### ISSUE TITLE
Assertion literal_index < PARSER_REGISTER_START || !has_context in parser_parse_for_statement_start

### ISSUE THREAD

**Issue by renatahodovan** [jerryscript-project/jerryscript#3579]
###### JerryScript revision
68909fc5

###### Build platform
Linux-4.15.0-74-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### Test case
```javascript
for (let i of $)
function $() {}
```

###### Output
```text
ICE: Assertion 'literal_index < PARSER_REGISTER_START || !has_context' failed at jerryscript/jerry-core/parser/js/js-parser-statm.c(parser_parse_for_statement_start):1373.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

###### Backtrace
```text
bt
#0  0xf7fd5079 in __kernel_vsyscall ()
#1  0xf77fc832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77fdcc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5657d290 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:30
#4  0x5662c5d7 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:63
#5  0x5662c618 in jerry_assert_fail (assertion=0x566e2e20 "literal_index < PARSER_REGISTER_START || !has_context", file=0x566e2240 "jerryscript/jerry-core/parser/js/js-parser-statm.c", function=0x566d1260 <__func__.5807.lto_priv.236> "parser_parse_for_statement_start", line=1373) at jerryscript/jerry-core/jrt/jrt-fatals.c:87
#6  0x565b3fe1 in parser_parse_for_statement_start.lto_priv.224 (context_p=0xffffc4a0) at jerryscript/jerry-core/parser/js/js-parser-statm.c:1373
#7  0x5657054c in parser_parse_statements (context_p=0xffffc4a0) at jerryscript/jerry-core/parser/js/js-parser-statm.c:2868
#8  0x5663ad5f in parser_parse_source (arg_list_p=0x0, arg_list_size=0, source_p=0x56738760 <buffer.lto_priv> "'use strict' ; \ntry { eval ( 'for (var i = 0 in {}) {}' ) ; \nString ( false ) ; \n} catch ( e ) { String ( e instanceof SyntaxError ) ; \n} \ntry { eval ( 'for (var = i of {}) {}' ) ; \nString ( false ) ;"..., source_size=701, parse_opts=0, error_location_p=0xffffc6b0) at jerryscript/jerry-core/parser/js/js-parser.c:2113
#9  0x5663e334 in parser_parse_script (arg_list_p=0x0, arg_list_size=0, source_p=0x56738760 <buffer.lto_priv> "'use strict' ; \ntry { eval ( 'for (var i = 0 in {}) {}' ) ; \nString ( false ) ; \n} catch ( e ) { String ( e instanceof SyntaxError ) ; \n} \ntry { eval ( 'for (var = i of {}) {}' ) ; \nString ( false ) ;"..., source_size=701, parse_opts=0, bytecode_data_p=0xffffc770) at jerryscript/jerry-core/parser/js/js-parser.c:2624
#10 0x566910f8 in jerry_parse (resource_name_p=0xffffcd93 "/home/reni/.fuzzinator_16690//jerryscript/picireny/112064616884918566181845407146609092378.js", resource_name_length=93, source_p=0x56738760 <buffer.lto_priv> "'use strict' ; \ntry { eval ( 'for (var i = 0 in {}) {}' ) ; \nString ( false ) ; \n} catch ( e ) { String ( e instanceof SyntaxError ) ; \n} \ntry { eval ( 'for (var = i of {}) {}' ) ; \nString ( false ) ;"..., source_size=701, parse_opts=0) at jerryscript/jerry-core/api/jerry.c:445
#11 0x5668dcd9 in main (argc=2, argv=0xffffcb24) at jerryscript/jerry-main/main-unix.c:739
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by rerobika** [comment]
Fixed via #3614.
