### ISSUE TITLE
Assertion !ecma_op_function_args_has_flag (arguments_list_p, ECMA_FUNC_ARG_FLAG_CONSTRUCT_SUPER) in ecma_op_function_call_external

### ISSUE THREAD

**Issue by renatahodovan** [jerryscript-project/jerryscript#3588]
###### JerryScript revision
9b393ee2

###### Build platform
Linux-4.15.0-74-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### Test case
```javascript
class A extends Uint8Array {
    f() {}
}

class C extends gc {
    h() {}
}
new C
```

###### Output
```text
ICE: Assertion '!ecma_op_function_args_has_flag (arguments_list_p, ECMA_FUNC_ARG_FLAG_CONSTRUCT_SUPER)' failed at jerryscript/jerry-core/ecma/operations/ecma-function-object.c(ecma_op_function_call_external):1084.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

###### Backtrace
```text
bt
#0  0xf7fd5079 in __kernel_vsyscall ()
#1  0xf77fc832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77fdcc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5657d319 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:30
#4  0x5662cdfa in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:63
#5  0x5662ce3b in jerry_assert_fail (assertion=0x566f5ee0 "!ecma_op_function_args_has_flag (arguments_list_p, ECMA_FUNC_ARG_FLAG_CONSTRUCT_SUPER)", file=0x566f5420 "jerryscript/jerry-core/ecma/operations/ecma-function-object.c", function=0x566bf360 <__func__.6569.lto_priv.656> "ecma_op_function_call_external", line=1084) at jerryscript/jerry-core/jrt/jrt-fatals.c:87
#6  0x5664d637 in ecma_op_function_call_external (func_obj_p=0xf5f00a60, this_arg_value=4124050579, arguments_list_p=0xffffc6c2, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1084
#7  0x5664e5ae in ecma_op_function_construct (func_obj_p=0xf5f00a60, this_arg_value=4124050579, arguments_list_p=0xffffc6c2, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1466
#8  0x5664e35e in ecma_op_function_construct (func_obj_p=0xf5f00520, this_arg_value=4124050579, arguments_list_p=0xffffc6c0, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1427
#9  0x5660e587 in opfunc_construct.lto_priv.460 (frame_ctx_p=0xffffc690) at jerryscript/jerry-core/vm/vm.c:831
#10 0x565d7f23 in vm_execute (frame_ctx_p=0xffffc690) at jerryscript/jerry-core/vm/vm.c:4221
#11 0x565d8456 in vm_run (bytecode_header_p=0xf4f03ec0, this_binding_value=4126149459, lex_env_p=0xf5d00590, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:4302
#12 0x5660c7b3 in vm_run_global (bytecode_p=0xf4f03ec0) at jerryscript/jerry-core/vm/vm.c:320
#13 0x56691ff8 in jerry_run (func_val=4126148739) at jerryscript/jerry-core/api/jerry.c:593
#14 0x5668e5c9 in main (argc=2, argv=0xffffcb24) at jerryscript/jerry-main/main-unix.c:748
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by galpeter** [comment]
Just for the record, the more minimized test case is:
```js
class C extends gc { }
new C ()
```
where `gc` could be (almost) any C native function.
