### ISSUE TITLE
Assertion context_p->next_scanner_info_p->source_p == context_p->source_p in parser_parse_function_statement

### ISSUE THREAD

**Issue by renatahodovan** [jerryscript-project/jerryscript#3714]
###### JerryScript revision
409e1fec

###### Build platform
Linux-4.15.0-88-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### Test case
```javascript
function $() {
    if ($)
    function
}
```

###### Output
```text
ICE: Assertion 'context_p->next_scanner_info_p->source_p == context_p->source_p' failed at jerryscript/jerry-core/parser/js/js-parser-statm.c(parser_parse_function_statement):625.
Error: ERR_FAILED_INTERNAL_ASSERTION
ASAN:DEADLYSIGNAL
=================================================================
==3351==ERROR: AddressSanitizer: ABRT on unknown address 0x00000d17 (pc 0xf7f05079 bp 0xffc0dcbc sp 0xffc0dca0 T0)
    #0 0xf7f05078  (linux-gate.so.1+0x1078)
    #1 0xf7f05078  (linux-gate.so.1+0x1078)
    #2 0xf772c831 in raise (/lib/i386-linux-gnu/libc.so.6+0x2d831)
    #3 0xf772dcc0 in abort (/lib/i386-linux-gnu/libc.so.6+0x2ecc0)
    #4 0x56632f33 in jerry_port_fatal jerryscript/jerry-port/default/default-fatal.c:30
    #5 0x566e8be6 in jerry_fatal jerryscript/jerry-core/jrt/jrt-fatals.c:63
    #6 0x566e8c27 in jerry_assert_fail jerryscript/jerry-core/jrt/jrt-fatals.c:87
    #7 0x566595b8 in parser_parse_function_statement jerryscript/jerry-core/parser/js/js-parser-statm.c:625
    #8 0x56664a84 in parser_parse_statements jerryscript/jerry-core/parser/js/js-parser-statm.c:2806
    #9 0x566fa46d in parser_parse_function jerryscript/jerry-core/parser/js/js-parser.c:2437
    #10 0x5665a1f6 in parser_parse_function_statement jerryscript/jerry-core/parser/js/js-parser-statm.c:792
    #11 0x56664a84 in parser_parse_statements jerryscript/jerry-core/parser/js/js-parser-statm.c:2806
    #12 0x566f7b23 in parser_parse_source jerryscript/jerry-core/parser/js/js-parser.c:2146
    #13 0x566fb127 in parser_parse_script jerryscript/jerry-core/parser/js/js-parser.c:2657
    #14 0x5674cb1d in jerry_parse jerryscript/jerry-core/api/jerry.c:448
    #15 0x5674972d in main jerryscript/jerry-main/main-unix.c:750
    #16 0xf7717e80 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18e80)
    #17 0x56626130  (jerryscript/build_gcc_asan_es2015/bin/jerry+0x1a130)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT (linux-gate.so.1+0x1078) 
==3351==ABORTING
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by dbatyai** [comment]
Resolved by #3755.
