### ISSUE TITLE
Assertion 'context.stack_top_uint8 == CBC_MAXIMUM_BYTE_VALUE && context.stack.last_position == 1 && context.stack.first_p != NULL && context.stack.first_p->next_p == NULL && context.stack.last_p == NULL' failed in parser_parse_source

### ISSUE THREAD

**Issue by renatahodovan** [jerryscript-project/jerryscript#3727]
###### JerryScript revision
90c7eccb

###### Build platform
Linux-4.15.0-88-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### Test case
```javascript
Function("a = 5, b, c = function() { for (var a = 0; a < 4; a++) ; return a; } ()", "eval ('super (a, b, c, d)')")
```

###### Output
```text
ICE: Assertion 'context.stack_top_uint8 == CBC_MAXIMUM_BYTE_VALUE && context.stack.last_position == 1 && context.stack.first_p != NULL && context.stack.first_p->next_p == NULL && context.stack.last_p == NULL' failed at jerryscript/jerry-core/parser/js/js-parser.c(parser_parse_source):2154.
Error: ERR_FAILED_INTERNAL_ASSERTION
ASAN:DEADLYSIGNAL
=================================================================
==8872==ERROR: AddressSanitizer: ABRT on unknown address 0x000022a8 (pc 0xf7f0e079 bp 0xffae27ec sp 0xffae27d0 T0)
    #0 0xf7f0e078  (linux-gate.so.1+0x1078)
    #1 0xf7f0e078  (linux-gate.so.1+0x1078)
    #2 0xf7735831 in raise (/lib/i386-linux-gnu/libc.so.6+0x2d831)
    #3 0xf7736cc0 in abort (/lib/i386-linux-gnu/libc.so.6+0x2ecc0)
    #4 0x565bef33 in jerry_port_fatal jerryscript/jerry-port/default/default-fatal.c:30
    #5 0x56674be6 in jerry_fatal jerryscript/jerry-core/jrt/jrt-fatals.c:63
    #6 0x56674c27 in jerry_assert_fail jerryscript/jerry-core/jrt/jrt-fatals.c:87
    #7 0x56683d7a in parser_parse_source jerryscript/jerry-core/parser/js/js-parser.c:2150
    #8 0x56687127 in parser_parse_script jerryscript/jerry-core/parser/js/js-parser.c:2657
    #9 0x566d245d in ecma_op_create_dynamic_function jerryscript/jerry-core/ecma/operations/ecma-function-object.c:263
    #10 0x56633f05 in ecma_builtin_function_dispatch_construct jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-function.c:74
    #11 0x566b74de in ecma_builtin_dispatch_construct jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1160
    #12 0x56690398 in ecma_op_function_construct jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1207
    #13 0x566577b4 in opfunc_construct.lto_priv.447 jerryscript/jerry-core/vm/vm.c:849
    #14 0x56618744 in vm_execute jerryscript/jerry-core/vm/vm.c:4109
    #15 0x56618c7e in vm_run jerryscript/jerry-core/vm/vm.c:4190
    #16 0x56655866 in vm_run_global jerryscript/jerry-core/vm/vm.c:321
    #17 0x566d91b5 in jerry_run jerryscript/jerry-core/api/jerry.c:596
    #18 0x566d579f in main jerryscript/jerry-main/main-unix.c:759
    #19 0xf7720e80 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18e80)
    #20 0x565b2130  (jerryscript/build_gcc_asan_es2015/bin/jerry+0x1a130)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT (linux-gate.so.1+0x1078) 
==8872==ABORTING
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by dbatyai** [comment]
Resolved by #3754.
