### ISSUE TITLE
Assertion context_p->next_scanner_info_p->type == SCANNER_TYPE_FUNCTION

### ISSUE THREAD

**Issue by rerobika** [jerryscript-project/jerryscript#3882]
###### JerryScript revision
585332f0

###### Build platform
Linux-5.3.0-53-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset \
```

###### Test case
```javascript

if($``())try{ }catch($‌){for(let{[function(){}]:{}}=()=>{}in[]^null)
```

###### Output
```text
ICE: Assertion 'context_p->next_scanner_info_p->type == SCANNER_TYPE_FUNCTION' failed at jerryscript//jerry-core/parser/js/js-parser.c(parser_parse_function_arguments):1710.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

###### Backtrace
```text
bt
#0  0xf7fd5b59 in __kernel_vsyscall ()
#1  0xf781b832 in __libc_signal_restore_set (set=0xffffb35c) at ../sysdeps/unix/sysv/linux/nptl-signals.h:80
#2  __GI_raise (sig=6) at ../sysdeps/unix/sysv/linux/raise.c:48
#3  0xf781ccc1 in __GI_abort () at abort.c:79
#4  0x5657c4b3 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript//jerry-port/default/default-fatal.c:30
#5  0x5663288c in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript//jerry-core/jrt/jrt-fatals.c:63
#6  0x566328cd in jerry_assert_fail (assertion=0x5670d380 "context_p->next_scanner_info_p->type == SCANNER_TYPE_FUNCTION", file=0x5670c900 "jerryscript//jerry-core/parser/js/js-parser.c", function=0x566e10c0 <__func__.5975.lto_priv.512> "parser_parse_function_arguments", line=1710) at jerryscript//jerry-core/jrt/jrt-fatals.c:87
#7  0x5663ecf5 in parser_parse_function_arguments (context_p=0xffffc150, end_type=LEXER_RIGHT_PAREN) at jerryscript//jerry-core/parser/js/js-parser.c:1710
#8  0x56644177 in parser_parse_function (context_p=0xffffc150, status_flags=14) at jerryscript//jerry-core/parser/js/js-parser.c:2444
#9  0x565d67a8 in lexer_construct_function_object (context_p=0xffffc150, extra_status_flags=14) at jerryscript//jerry-core/parser/js/js-lexer.c:2665
#10 0x565919b7 in parser_parse_function_expression (context_p=0xffffc150, status_flags=14) at jerryscript//jerry-core/parser/js/js-parser-expr.c:1348
#11 0x56593fd4 in parser_parse_unary_expression (context_p=0xffffc150, grouping_level_p=0xffffb970) at jerryscript//jerry-core/parser/js/js-parser-expr.c:1818
#12 0x5659baf8 in parser_parse_expression (context_p=0xffffc150, options=4) at jerryscript//jerry-core/parser/js/js-parser-expr.c:3479
#13 0x5658ab77 in lexer_expect_object_literal_id (context_p=0xffffc150, ident_opts=8) at jerryscript//jerry-core/parser/js/js-lexer.c:3045
#14 0x5659a216 in parser_parse_object_initializer (context_p=0xffffc150, flags=(PARSER_PATTERN_BINDING | PARSER_PATTERN_TARGET_ON_STACK | PARSER_PATTERN_LET)) at jerryscript//jerry-core/parser/js/js-parser-expr.c:3192
#15 0x5659ab4e in parser_parse_initializer_by_next_char (context_p=0xffffc150, flags=(PARSER_PATTERN_BINDING | PARSER_PATTERN_TARGET_ON_STACK | PARSER_PATTERN_LET)) at jerryscript//jerry-core/parser/js/js-parser-expr.c:3302
#16 0x565a7a25 in parser_parse_for_statement_start (context_p=0xffffc150) at jerryscript//jerry-core/parser/js/js-parser-statm.c:1357
#17 0x565af2f1 in parser_parse_statements (context_p=0xffffc150) at jerryscript//jerry-core/parser/js/js-parser-statm.c:2913
#18 0x56641a16 in parser_parse_source (arg_list_p=0x0, arg_list_size=0, source_p=0x56757d00 <buffer.lto_priv> "if(new0xD2&&{}++^this``().package)try{}catch($‌){for(let{[function(){}]:class{},ற,}=_+()=>{}in[,,,,,,]^null)for({},[,,],class{},{};;){};}finally{}const[,,]=void++$‌=>{}``&--functionଢ︴(){},[."..., source_size=728, parse_opts=0, error_location_p=0xffffc380) at jerryscript//jerry-core/parser/js/js-parser.c:2182
#19 0x5664584e in parser_parse_script (arg_list_p=0x0, arg_list_size=0, source_p=0x56757d00 <buffer.lto_priv> "if(new0xD2&&{}++^this``().package)try{}catch($‌){for(let{[function(){}]:class{},ற,}=_+()=>{}in[,,,,,,]^null)for({},[,,],class{},{};;){};}finally{}const[,,]=void++$‌=>{}``&--functionଢ︴(){},[."..., source_size=728, parse_opts=0, bytecode_data_p=0xffffc440) at jerryscript//jerry-core/parser/js/js-parser.c:2818
#20 0x5669bd2b in jerry_parse (resource_name_p=0xffffca85 "/home/fancsikrobi/harmony/fuzzinator-configs/.fuzzinator-14169/jerryscript/picireny/674.js", resource_name_length=90, source_p=0x56757d00 <buffer.lto_priv> "if(new0xD2&&{}++^this``().package)try{}catch($‌){for(let{[function(){}]:class{},ற,}=_+()=>{}in[,,,,,,]^null)for({},[,,],class{},{};;){};}finally{}const[,,]=void++$‌=>{}``&--functionଢ︴(){},[."..., source_size=728, parse_opts=0) at jerryscript//jerry-core/api/jerry.c:447
#21 0x5669893b in main (argc=2, argv=0xffffc834) at jerryscript//jerry-main/main-unix.c:750
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by rerobika** [comment]
Reducing the testcase by hand also triggers the same assertion:

```js
for(let{[function(){}]:{}} = ()=>{} in [])
```
