### ISSUE TITLE
Invalid memory access (segfault) in opfunc_resume_executable_object in opcodes.c

### ISSUE THREAD

**Issue by ruc-fuzzer** [jerryscript-project/jerryscript#4189]
###### JerryScript revision
```
The master branch or git hash: c013fad
```

###### Build platform
```
Ubuntu 18.04.4 LTS  Linux 4.15.0-74-generic x86_64
```

###### Build steps
```
Build with ASAN enabled:
python tools/build.py  --compile-flag=-fsanitize=address --compile-flag=-g --strip=OFF
```
###### Test case
```
1 ; export default await 1
```

###### Output
```
ASAN:DEADLYSIGNAL
=================================================================
==7178==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000004 (pc 0x55555558d55f bp 0x555555855110 sp 0x7fffffffde50 T0)
==7178==The signal is caused by a READ memory access.
==7178==Hint: address points to the zero page.
    #0 0x55555558d55e in opfunc_resume_executable_object /home/user/Product/jerryscript/master/src/jerry-core/vm/opcodes.c:789
    #1 0x555555599dc4 in ecma_process_promise_async_reaction_job /home/user/Product/jerryscript/master/src/jerry-core/ecma/operations/ecma-jobqueue.c:319
    #2 0x555555599dc4 in ecma_process_all_enqueued_jobs /home/user/Product/jerryscript/master/src/jerry-core/ecma/operations/ecma-jobqueue.c:529
    #3 0x55555556cb80 in jerry_run_all_enqueued_jobs /home/user/Product/jerryscript/master/src/jerry-core/api/jerry.c:626
    #4 0x55555556cb80 in main /home/user/Product/jerryscript/master/src/jerry-main/main-unix.c:286
    #5 0x7ffff6a4ab96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #6 0x55555556d5d9 in _start (/home/user/Product/jerryscript/master/src/build/bin/jerry+0x195d9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/user/Product/jerryscript/master/src/jerry-core/vm/opcodes.c:789 in opfunc_resume_executable_object
==7178==ABORTING
```

**Comment by ossy-szeged** [comment]
Still valid on latest master ( 0ffe1665bd0ee457dd4c1083811e1592a5e2908d ).
ICE: Assertion 'jmem_is_heap_pointer (pointer_p)' failed at /home/oszi/jerryscript/jerry-core/jmem/jmem-allocator.c(jmem_compress_pointer):182.
